### ISSUE TITLE
Error: bind EADDRINUSE 0.0.0.0:5224

### ISSUE THREAD

**Issue by nickbrown20** [stfnhmplr/homebridge-synology#23] opened 2017-05-21 21:19 UTC
Hi,

It appears that the harmony hub plugin also uses port 5224, is there anyway i can change the port number for this plugin? I tried changing the port number to 5225 in the config.json, but that feels too simple (and does not work). Ideally i would like to use both harmony and synology together...

Nick

**Comment by stfnhmplr** [comment] 2017-05-23 06:08
Hi,

i think the issue is related to the harmony plugin. I don't bind a additional port since i don't use the homebridge api for a dynamic platform. The port number in your config.json file should match the port of your  synologys webinterface.

There are some open issues at the harmony-plugin related to port 5224. Maybe you take a look at them. So i'll close this.

**Closed** 2017-05-23 06:08 UTC
